name: FTP Deploy to Hostinger

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - 'index.html'
      - 'raizes/index.html'
      - 'belohorizonte/index.html'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install lftp
        run: sudo apt-get install -y lftp

      - name: Deploy index.html
        run: |
          lftp -c "
            set ftp:passive-mode true;
            set ssl:verify-certificate false;
            open -u u172337921.dpsimobiliario.pt,Dps2026# ftp://89.117.229.121;
            put -O / index.html;
            bye
          "

      - name: Deploy raizes/index.html
        run: |
          lftp -c "
            set ftp:passive-mode true;
            set ssl:verify-certificate false;
            open -u u172337921.dpsimobiliario.pt,Dps2026# ftp://89.117.229.121;
            put -O /raizes index.html < raizes/index.html;
            bye
          "

      - name: Deploy belohorizonte/index.html
        run: |
          lftp -c "
            set ftp:passive-mode true;
            set ssl:verify-certificate false;
            open -u u172337921.dpsimobiliario.pt,Dps2026# ftp://89.117.229.121;
            put -O /belohorizonte index.html < belohorizonte/index.html;
            bye
          "
